# This is a basic workflow that is manually triggered

name: docker
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]
jobs:
  # This workflow contains a single job called "greet"
    
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - name: docker loguin 
      env:
        DOCKER_USER : ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{secrets.DOCKER_PWD }}   
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PWD
    - name: docker build
      run: |
        docker build . -t abdoubentegar/geii-backend
    - name: docker push
      run: |
        docker push abdoubentegar/geii-backend
